name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

    - name: Run Unit Test
      run: make test

    - name: Check Linting
      run: make lint
